version: '3.11'

services:
  mongodb:
    image: mongo:6-jammy
    ports:
      - '27017:27017'
    volumes:
      - dbdata6:/data/db
      - ./mongodb/initdb.d/mong_init.js:/docker-entrypoint-initdb.d/mong_init.js:ro  # Mount mong_init.js
    environment:
      MONGO_INITDB_ROOT_USERNAME: medical_user
      MONGO_INITDB_ROOT_PASSWORD: securepassword
    healthcheck:
      test: ["CMD", "mongo", "--eval", "db.runCommand({ connectionStatus: 1 })"]
      interval: 10s
      retries: 5
      start_period: 30s
      timeout: 10s

  streamlit:
    build:
      context: ./streamlit  # Use Dockerfile in streamlit folder
      dockerfile: Dockerfile
    container_name: streamlit
    ports:
      - "9000:9000"
    volumes:
      - ./streamlit:/app
      - static_volume:/app/static  # Ensure static volume is in /app/static
    depends_on:
      - mongodb
    restart: always

volumes:
  dbdata6:
  static_volume:
